apiVersion: v1
kind: Service
metadata:
  name: vprodb

spec:
  ports:
    - port: 3306               # Define 'port' here
      targetPort: vprodb-port   # Define 'targetPort' inside the 'ports' list
      protocol: TCP

  selector:
    app: vprodb
  type: ClusterIP
